## CE7454 : Deep Learning for Data Science
## Xavier Bresson


## Coding Test 1
Date: October 7th, 2020<br>

*Instructions* <br>
Name: Do not forget to add your name to the notebook file "coding_test1_CE7454_YOUR_NAME.ipynb".<br>
Questions: This notebook has 10 questions.<br>
Answers: Write the answers to each question in this notebook.<br>
Type: This test is individual and open-book.<br>
Grading: 1 point for each question.<br>
Delivery: Upload your notebook to https://drive.google.com/drive/folders/1Owos8IyA2Mh2PGvRlTEJZuNmR7sJOpx-  by 6:20pm. <br>
Remark: **If certain conditions of the questions (for eg. hyperparameter values) are not stated, you are free to choose anything you want.**<br>


### Question 1

Create a PyTorch tensor $x$ of type FloatTensor, size [5, 2, 7] and filled with random numbers. Print tensor $x$ and its type. Convert the same tensor $x$ to type LongTensor and print its value and type.

In [1]:
%reset -f
import torch

# YOUR CODE HERE
x = torch.rand(5,2,7) 
print(x) 
print(x.type()) 

x = x.long() 
print(x) 
print(x.type()) 

tensor([[[0.9027, 0.2811, 0.3214, 0.8193, 0.4659, 0.9217, 0.7292],
         [0.7186, 0.1758, 0.5782, 0.4089, 0.7382, 0.6527, 0.1410]],

        [[0.1906, 0.3043, 0.8819, 0.4505, 0.5401, 0.0906, 0.1059],
         [0.9855, 0.4273, 0.5631, 0.5184, 0.2020, 0.5849, 0.5355]],

        [[0.6341, 0.4142, 0.5412, 0.5758, 0.1747, 0.8109, 0.8266],
         [0.5400, 0.2497, 0.2317, 0.2189, 0.3120, 0.2294, 0.0174]],

        [[0.2345, 0.4870, 0.8494, 0.4145, 0.7121, 0.5540, 0.0606],
         [0.6180, 0.6153, 0.5141, 0.7828, 0.0452, 0.4175, 0.6792]],

        [[0.5229, 0.9023, 0.0013, 0.9073, 0.6936, 0.3938, 0.5412],
         [0.3752, 0.4362, 0.1190, 0.8652, 0.5501, 0.5963, 0.0562]]])
torch.FloatTensor
tensor([[[0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0],
      

### Question 2

Compute and print the matrix product of matrices A and B given below.

Compute and print the element-wise product of matrices C and D given below.


In [2]:
%reset -f
import torch

A=torch.ones(2,3)
B=torch.ones(3,2)
C=torch.ones(2,2)
D=torch.ones(2,2)

# YOUR CODE HERE
print(torch.mm(A,B))
print(C*D)

tensor([[3., 3.],
        [3., 3.]])
tensor([[1., 1.],
        [1., 1.]])


### Question 3

Given a minibatch $x$ of color images represented by a tensor of size (100, 3, 28, 28), with 3 color channels (red, green and blue), a grid domain of 28 pixels by 28 pixels, and 100 images in the minibatch. 

Transform the tensor $x$ into a vector and print its size.

Transform back the vector to a tensor of size (100, 3, 28, 28) and print its size.

In [3]:
%reset -f
import torch

x = torch.rand(100,3,28,28) # given minibatch of color images 

# YOUR CODE HERE
vectorized_x = x.view(235200) # 28*28*3*100 = 235200
print(vectorized_x.size())

original_x = vectorized_x.view(100,3,28,28)
print(original_x.size())

torch.Size([235200])
torch.Size([100, 3, 28, 28])


### Question 4

Consider a minibatch $s$ of scores of size (100,5) with 5 classes and 100 data points. Convert the scores into probabilities with the softmax operator. Print the scores and the probabilities for the 10th data point (reminder: 1st data point is indexed by 0). 

Implement a Python function that returns the indices of the classes corresponding to the highest probability for each data in the minibatch. Note that the 5 classes are indexed with integer values $\{0,1,2,3,4\}$. Print the index of the highest probability for the 10th data point.


In [4]:
%reset -f
import torch

s = torch.FloatTensor(100,5).uniform_(-1,5)

# YOUR CODE HERE
prob = torch.softmax(s, dim=1)
print(s[10-1,:])
print(prob[10-1,:])

def return_max_index(prob):
    index_max_prob = torch.argmax(prob, dim=1)
    return index_max_prob
index_max_prob = return_max_index(prob)
print(index_max_prob[10-1])


tensor([-0.7123,  4.3702,  0.1516,  1.4458,  4.0933])
tensor([0.0034, 0.5456, 0.0080, 0.0293, 0.4137])
tensor(1)


### Question 5

Implement the activation function $$\sigma(x)=\frac{2}{2+e^{-x}}$$ as a Python function.

Print the activation values of the input tensor x1=$[-4.5,1.2,0.0,6.2]$ with function $\sigma$. 

Compute the analytical derivative of $\sigma$ and implement it as a Python function. 

$$\sigma'(x)=\textrm{to be computed}$$

$$\sigma'(x)=\frac{2e^{-x}}{(2+e^{-x})^2} \quad\textrm{ SOLUTION}$$

Print the values of the input tensor x2=$[2.3,-1.9,-3.4,6.2]$ with function $\sigma'$.


In [5]:
%reset -f
import torch

x1 = torch.Tensor([-4.5,1.2,0.0,6.2])
x2 = torch.Tensor([2.3,-1.9,-3.4,6.2])

# YOUR CODE HERE
def sigma(x):
    return 2/ (2 + torch.exp(-x))
print(sigma(x1))

def derivative_sigma(x):
    return 2*torch.exp(-x)/ (2+torch.exp(-x))**2
print(derivative_sigma(x2))

tensor([0.0217, 0.8691, 0.6667, 0.9990])
tensor([0.0455, 0.1772, 0.0587, 0.0010])


### Question 6

Implement a 2-layer MLP with the non-linear activation function $\sigma$ from Question 5. The output score of the network is defined as

$$s = W_2\sigma(W_1 x + b_1)+b_2$$

The size of tensor $x$ is 2 and the size of tensor $s$ is 3.

Tensor $W_1$ is a matrix of ones and size (10,2) and tensor $W_2$ is a matrix of ones and size (3,10). 

Tensors $b_1$ and $b_2$ are vectors of zeros with their sizes constrained by $W_1$ and $W_2$.

Print the output tensor $s$ for the input $x=[2.3,-1.4]$. 

In [6]:
%reset -f
import torch
import torch.nn as nn

x = torch.Tensor([2.3,-1.4])

# YOUR CODE HERE
def sigma(x):
    return 2/ (2 + torch.exp(-x))

class two_layer_MLP(nn.Module):
    def __init__(self, in_features, hidden_features, out_features):
        super(two_layer_MLP, self).__init__()
        self.linear1 = nn.Linear(in_features, hidden_features)
        self.linear2 = nn.Linear(hidden_features, out_features)
        self.linear1.weight.data.fill_(1.0)
        self.linear1.bias.data.fill_(0.0)
        self.linear2.weight.data.fill_(1.0)
        self.linear2.bias.data.fill_(0.0)
    def forward(self, x):
        y1 = self.linear1(x)
        y2 = sigma(y1)
        s = self.linear2(y2)
        return s

net = two_layer_MLP(2,10,3)
s = net(x)
print(s,s.size())

tensor([8.3106, 8.3106, 8.3106], grad_fn=<AddBackward0>) torch.Size([3])


### Question 7

Given a minibatch $s=[ [5.2,-1.2], [-1.0,4.0], [-1,2] ]$ of scores of three data points and two classes, implement and compute the mean cross entropy for the labels $[0,1,1]$.

As a reminder, the definition of the mean cross entropy loss is 

$$ L = -\frac{1}{N}\sum_{i=1}^N \log \Big(\textrm{entry cl($i$) of probability vector } p^{(i)} \Big)$$

where $cl($i$)$ is the class index of the $i^{th}$ training data and $p^{(i)}$ is the probability vector computed by the network (using the score vector).

Note that your implementation of the cross entropy cannot use the PyTorch function 'nn.CrossEntropyLoss'. 

In [7]:
%reset -f
import torch
import torch.nn as nn

s = torch.Tensor( [ [5.2,-1.2], [-1.0,4.0], [-1,2] ] )
label = torch.LongTensor([0,1,1])

# YOUR CODE HERE
p = torch.softmax(s, dim=1)
log_prob = -torch.log(p)
mean_cross_entropy = log_prob[torch.arange(3),label].mean()
print(mean_cross_entropy)
print(nn.CrossEntropyLoss()(s,label)) # double checking

tensor(0.0190)
tensor(0.0190)


### Question 8

Implement a new class for the sigma function $\sigma$ defined in Question 5. Precisely, define explicitely the forward pass and the backward pass for this new class. Hint: https://pytorch.org/tutorials/beginner/examples_autograd/two_layer_net_custom_function.html

Print the output value $y=\sigma(x)$ for the tensor $x=[1.6,-1.2,0.0,4.0]$.

Consider the loss to be 

$$ L = \frac{1}{m}\sum_{j=1}^m y_j^2,\quad y_j=\sigma(x_j)$$

where $x_1=1.6, x_2=-1.2, x_3=0.0, x_4=4.0$.

Print the gradient value $\frac{dL}{dx}$ for $x=[1.6,-1.2,0.0,4.0]$.


In [8]:
%reset -f
import torch

x = torch.Tensor([1.6,-1.2,0.0,4.0])

# YOUR CODE HERE
class sigma(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        ctx.save_for_backward(x)
        return 2/ (2 + torch.exp(-x))
    @staticmethod
    def backward(ctx, grad_output):
        x, = ctx.saved_tensors
        local_derivative = 2*torch.exp(-x)/ (2+torch.exp(-x))**2
        grad_input = grad_output.clone()
        grad_input = grad_output* local_derivative
        return grad_input

sigma_fc = sigma.apply
x = x.requires_grad_()
y = sigma_fc(x)
print(y)

loss = (y**2).mean()
loss.backward()
print(x.grad)

tensor([0.9083, 0.3759, 0.6667, 0.9909], grad_fn=<sigmaBackward>)
tensor([0.0378, 0.0441, 0.0741, 0.0045])


### Question 9

Implement a class of 3-layer MLP with ReLU activation :

$$s = W_3\textrm{ ReLU}(W_2\textrm{ ReLU}(W_1 x + b_1)+b_2)+b_3)$$

Instantiate a network with 784 as input dimension, 50 as hidden dimension and 10 as output dimension.

During training, only the last linear layer will be trained (the first two linear layers will not be trained and will keep the same initial values during training). 

Use 10 epochs to train the network with batch size 100 and learning rate 0.01. Print the loss and error of classification of the training set after 10 epochs.

In [9]:
%reset -f
import torch
import torch.nn as nn
from utils import *
data_path=check_mnist_dataset_exists()
train_data=torch.load(data_path+'mnist/train_data.pt')
train_label=torch.load(data_path+'mnist/train_label.pt')

# YOUR CODE HERE
class three_layer_MLP(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(three_layer_MLP , self).__init__()
        self.layer1 = nn.Linear(  input_size, hidden_size )
        self.layer2 = nn.Linear(  hidden_size, hidden_size )
        self.layer3 = nn.Linear(  hidden_size, output_size )
    def forward(self, x):
        x = self.layer1(x)
        x = torch.relu(x)
        x = self.layer2(x)
        x = torch.relu(x)
        score = self.layer3(x)
        return score

net = three_layer_MLP(784,50,10)

params_to_update = []
params_to_update.append(net.layer3.weight)
params_to_update.append(net.layer3.bias)
optimizer=torch.optim.SGD( params_to_update , lr=0.01 )

bs = 100

criterion = nn.CrossEntropyLoss()

for epoch in range(10):
    running_loss=0
    running_error=0
    num_batches=0
    shuffled_indices=torch.randperm(60000)
    for count in range(0,60000,bs):
        optimizer.zero_grad()
        indices = shuffled_indices[count:count+bs]
        minibatch_data = train_data[indices]
        minibatch_label = train_label[indices]
        inputs = minibatch_data.view(bs,784)
        inputs.requires_grad_()
        scores = net( inputs ) 
        loss = criterion( scores , minibatch_label) 
        loss.backward()
        optimizer.step()
        running_loss += loss.detach().item()
        error = get_error( scores.detach() , minibatch_label)
        running_error += error.item()
        num_batches+=1
    total_loss = running_loss/num_batches
    total_error = running_error/num_batches
    print('epoch=',epoch, ' loss=', total_loss , ' error=', total_error*100)

        

epoch= 0  loss= 2.300812317530314  error= 87.32666656374931
epoch= 1  loss= 2.295027406613032  error= 87.53499990701675
epoch= 2  loss= 2.290812224149704  error= 88.30833312869072
epoch= 3  loss= 2.2869838837782543  error= 87.24833328525226
epoch= 4  loss= 2.2832719520727793  error= 85.53000021974245
epoch= 5  loss= 2.279603095849355  error= 83.49333370725314
epoch= 6  loss= 2.2759684161345164  error= 82.12666707237561
epoch= 7  loss= 2.272345388730367  error= 80.03000003099442
epoch= 8  loss= 2.268751895427704  error= 78.80166686574618
epoch= 9  loss= 2.2651789593696594  error= 76.64833350976308


### Question 10

Use the class of 3-layer MLP with ReLU activation implemented in Question 9. 

We will train the network with the quality loss defined as

$$ L = \Big( \Pi_{i=1}^N \textrm{entry cl($i$) of probability vector } p^{(i)} \Big)^{1/N}$$

where $cl($i$)$ is the class index of the $i^{th}$ training data and $p^{(i)}$ is the probability vector computed by the network.

Unlike Question 9, all linear layers will be learned during training. 

Use 10 epochs to train the network with batch size 25 and learning rate 0.01. Print the loss and error of classification of the training set after 10 epochs.


In [10]:
%reset -f
import torch
import torch.nn as nn
from utils import *
data_path=check_mnist_dataset_exists()
train_data=torch.load(data_path+'mnist/train_data.pt')
train_label=torch.load(data_path+'mnist/train_label.pt')

# YOUR CODE HERE
class three_layer_MLP(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(three_layer_MLP , self).__init__()
        self.layer1 = nn.Linear(  input_size, hidden_size )
        self.layer2 = nn.Linear(  hidden_size, hidden_size )
        self.layer3 = nn.Linear(  hidden_size, output_size )
    def forward(self, x):
        x = self.layer1(x)
        x = torch.relu(x)
        x = self.layer2(x)
        x = torch.relu(x)
        score = self.layer3(x)
        return score

net = three_layer_MLP(784,50,10)
optimizer=torch.optim.SGD( net.parameters() , lr=0.01 )
bs = 25

for epoch in range(10):
    running_loss=0
    running_error=0
    num_batches=0
    shuffled_indices=torch.randperm(60000)
    for count in range(0,60000,bs):
        optimizer.zero_grad()
        indices=shuffled_indices[count:count+bs]
        minibatch_data =  train_data[indices]
        minibatch_label= train_label[indices]
        inputs = minibatch_data.view(bs,784)
        inputs.requires_grad_()
        scores=net( inputs ) 

        p = torch.softmax(scores,dim=1)
        p = p[torch.arange(bs),minibatch_label]
        loss = -p.prod()**(1/float(bs))
        loss.backward()
        optimizer.step()
        
        running_loss += loss.detach().item()
        error = get_error( scores.detach() , minibatch_label)
        running_error += error.item()
        num_batches+=1
    total_loss = running_loss/num_batches
    total_error = running_error/num_batches
    print('epoch=',epoch, ' loss=', -total_loss , ' error=', total_error*100)

epoch= 0  loss= 0.10458569578205545  error= 76.01333390176296
epoch= 1  loss= 0.14501238784131903  error= 49.24333333472411
epoch= 2  loss= 0.4548073540938397  error= 20.8283333654205
epoch= 3  loss= 0.6796698375294606  error= 11.408333711326122
epoch= 4  loss= 0.728869843557477  error= 9.44000040491422
epoch= 5  loss= 0.7560911426258584  error= 8.473333758612474
epoch= 6  loss= 0.7769464354154965  error= 7.681667086978754
epoch= 7  loss= 0.7945305673778057  error= 6.905000393589337
epoch= 8  loss= 0.8106508443504572  error= 6.311667154232661
epoch= 9  loss= 0.8253588288587829  error= 5.76000043998162
